FROM alpine:3.13

RUN apk --update add --no-cache openssl vim bash

RUN mkdir -p /my_app

WORKDIR /my_app

COPY . .

EXPOSE 54321

ENTRYPOINT [ "/bin/sh", "docker-entrypoint-tls-server-revoked-cert.sh" ]
